name: Deploy to CurseForge
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to checkout and deploy'
        required: true

jobs:
  checks:
    name: Deploy to CurseForge (${{ github.event.inputs.tag }})
    runs-on: ubuntu-latest
    env:
      GITHUB_TAG: ${{ github.event.inputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Restore cached Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build

      - name: Generate change log
        run: ./gradlew generateChangelog

      - name: Deploy to CurseForge (Curse)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
          CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
        run: ./gradlew deployCurseForge

      - name: Cleanup Gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
